### ISSUE TITLE
TableList show default data onload

### ISSUE THREAD

**Issue by buksy90** [buksy90/ksl#38]
Update table list page ( http://localhost:3000/tabulka ) to show teams standings by default when page is loaded. 

AC: When Im on "Uvod" page and I click on "Tabuľky" in menu then I want to teams table to be shown by default so I dont have to click on "Poradie timov" button

**Comment by MJuhas** [comment]
If i know this issues is done and merge in the master, or  I have  make some changes, else  ?

**Comment by buksy90** [comment]
I dont understand your question

**Comment by MJuhas** [comment]
ouu, why you dont close request, when it is finished
